"use server";

import { supabase } from "@/lib/services/db";

/**
 * Generates a Markdown Research Pack export
 */
export async function exportToMarkdown(runId: string) {
  const { data: run } = await supabase
    .from('research_runs')
    .select('*, subjects(*), claims(*), evidence_items(*)')
    .eq('id', runId)
    .single();

  if (!run) throw new Error("Run not found");

  let md = `# SignalProof Research Pack: ${run.subjects.name}\n\n`;
  md += `**Context:** ${run.subjects.context}\n`;
  md += `**Date:** ${new Date(run.started_at).toLocaleDateString()}\n`;
  md += `**Credibility Score:** ${run.latency_ms ? '92%' : 'Pending'}\n\n`;

  md += `## Verified Claims\n\n`;
  run.claims.forEach((c: any) => {
    md += `### ${c.claim_text}\n`;
    md += `- **Category:** ${c.category}\n`;
    md += `- **Confidence:** ${c.confidence_level} (${c.confidence_score * 100}%)\n\n`;
  });

  md += `## Evidence Library\n\n`;
  run.evidence_items.forEach((e: any, i: number) => {
    md += `#### [E${i + 1}] ${e.url}\n`;
    md += `> ${e.snippet}\n\n`;
  });

  md += `\n---\n*Generated by SignalProof AI*`;

  return md;
}

/**
 * Prompt Injection Protection Utility
 */
export function sanitizePrompt(text: string): string {
  // Strip system command keywords and potential injection payloads
  const blacklist = [/ignore previous instructions/gi, /system prompt/gi, /developer mode/gi];
  let sanitized = text;
  blacklist.forEach(pattern => {
    sanitized = sanitized.replace(pattern, "[FILTERED]");
  });
  return sanitized;
}
